spring.application.name=rescue-gatitos-to-work
spring.datasource.url=jdbc:h2:mem:gatitosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

api.security.token.secret=${JWT_SECRET:default}